### ISSUE TITLE
it needs python2 to compile

### ISSUE THREAD

**Issue by rchikhi** [fenderglass/ABruijn#25]
with python3: 
```
Flye$ python setup.py build
  File "setup.py", line 16
    print "Compilation error: ", e
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Compilation error: ", e)?

```

**Comment by mikolmogorov** [comment]
Thank you! Flye currently only works with Python 2.7. We have added python version check into the installation script.

**Comment by xlinxlin** [comment]
Hi @fenderglass, do you have any plan to make it works with python3?

**Comment by mikolmogorov** [comment]
Hi,

It is not in our plans currently - this is a lot of work, but seems that the most of the people are happy with Python2. Are there any practical reasons you would prefer python3 to python2? If there are any issues with installation - you can always use the bioconda package.

**Comment by xlinxlin** [comment]
Hi, because all the other essential tools like porechop, NanoFilt and NanoStat are used in my pipeline are written in python3 and I am running anaconda environment with python3.6, so I would be delighted to see Flye is also compatible with python3.

**Comment by xlinxlin** [comment]
Hi, it is OK now, I run it in anaconda environment with python2.7.

**Comment by mikolmogorov** [comment]
Yes, separate Python 2 and 3 environment should work. I guess that would be more convenient to have everything in one environment though - probably we should migrate to Python 3 sooner or later..
